# 项目相关配置
hzdl:
  # 名称
  name: edg
  # 版本
  version: 1.0.0
  # 版权年份
  copyright-year: 2020
  # 实例演示开关
  demo-enabled: true
  # 文件路径 示例（ Windows配置D:/hzdl/uploadPath，Linux配置 /home/hzdl/uploadPath）
#  profile: D:/upload/edg
  profile: /home/hzdl/uploadPath
  # 获取ip地址开关
  address-enabled: false
  # 验证码类型 math 数组计算 char 字符验证
  captcha-type: math


# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8080
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值25
      min-spare: 30

# 日志配置
logging:
  level:
    com.hzdl: debug
    org.springframework: warn

# Spring配置
spring:
  jackson:
    # 日期格式化
    date-format: yyyy-MM-dd HH:mm:ss
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  profiles:
    active: druid
  # 文件上传
  servlet:
     multipart:
       # 单个文件大小
       max-file-size:  10MB
       # 设置总上传的文件大小
       max-request-size:  20MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  # redis 配置
  redis:
    # 地址
    host: 10.112.56.65
    # 端口，默认为6379
    port: 6379
    # 密码
    password: 123456
    # 连接超时时间
    timeout: 20s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms

# token配置
token:
    # 令牌自定义标识
    header: Authorization
    # 令牌密钥
    secret: abcdefghijklmnopqrstuvwxyz
    # 令牌有效期（默认300分钟）
    expire-time: 300

# mybatis-plus配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.hzdl.**.domain

# PageHelper分页插件
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

# Swagger配置
swagger:
  # 是否开启swagger
  enabled: true
  # 要扫描的包，多个包之间以英文逗号隔开
  base-package: com.hzdl.api,com.hzdl.cms,com.hzdl.edg

# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice/*
  # 匹配链接
  url-patterns: /system/*,/monitor/*,/tool/*

# 开放权限
ignore-url:
  url:
    - /api/** # 对外提供的接口
